
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace aspdev.repaem.Models.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public int Id { get; set; }

    public Nullable<int> ClientId { get; set; }

    public string Text { get; set; }

    public Nullable<double> Rating { get; set; }

    public string RepBaseId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

}

}
