
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace aspdev.repaem.Models.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Distinct
{

    public int Id { get; set; }

    public string Name { get; set; }

    public int CityId { get; set; }

}

}
