//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdev.repaem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Id { get; set; }
        public int BaseId { get; set; }
        public int PriceId { get; set; }
        public string CommentId { get; set; }
        public string AddressPhoto { get; set; }
    }
}
