//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdev.repaem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserHostAddress { get; set; }
        public string UserHostName { get; set; }
        public string UserLanguages { get; set; }
        public string UserAgent { get; set; }
        public string UrlReferrer { get; set; }
        public string Browser { get; set; }
        public string Key { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
