//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspdev.repaem.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public System.Guid Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime Expires { get; set; }
        public string Host { get; set; }
        public string Cookie { get; set; }
    }
}
